//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QAssetBundle
{
    
    public class Configs
    {
        public const string BundleName = "configs";
        public const string CharacterDataConfig = "CharacterDataConfig";
        public const string MapData = "MapData";
    }
    public class Ui_game_inspector_prefab
    {
        public const string BundleName = "ui_game_inspector_prefab";
        public const string UI_Game_Inspector = "UI_Game_Inspector";
    }
    public class Ui_loading_prefab
    {
        public const string BundleName = "ui_loading_prefab";
        public const string UI_Loading = "UI_Loading";
    }
    public class Ui_menu_prefab
    {
        public const string BundleName = "ui_menu_prefab";
        public const string UI_Menu = "UI_Menu";
    }
}
