//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QAssetBundle
{
    
    public class Configs
    {
        public const string BundleName = "configs";
        public const string GameSettingConfig = "GameSettingConfig";
        public const string NetDataConfig = "NetDataConfig";
    }
    public class Ui_menupanel_prefab
    {
        public const string BundleName = "ui_menupanel_prefab";
        public const string UI_MenuPanel = "UI_MenuPanel";
    }
}
